services:

  # mysql:
  #   image: mysql:8.0
  #   container_name: notesapp_mysql
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: techbodia     
  #     MYSQL_USER: techbodia         
  #     MYSQL_PASSWORD: Techbodia@2026
  #     MYSQL_ROOT_PASSWORD: rootpassword123
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10

  backend:
    build: ./Backend
    container_name: notesapp_backend
    ports:
      - "5174:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Port=3306;Database=techbodia;User=techbodia;Password=Techbodia@2026;
      - Jwt__Key=THIS_IS_A_SUPER_SECRET_KEY_12345
      - Jwt__Issuer=BackendApi
      - Jwt__Audience=BackendApiUser
      - Jwt__ExpireMinutes=60
      - ASPNETCORE_ENVIRONMENT=Production
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    restart: always

  frontend:
    build: ./Frontend
    container_name: notesapp_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data: